# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95051d733dcd3d8aeb76f54e27ff9fdfdef5f9f56516ee3042084ec11605b1cfb01f4b10582f738941a81a09f9d3fc5d3e865d1e9107844d723f088ee6f15ad5

test:
  secret_key_base: f044fba99bed4b5faa4ea8c7639b21077e097553f3ccd2aee682fc9ad4ee3158517e388ffdde81c7c66d2293dbce894e54ec60ae3550f7e3a27fb68f53b62d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
